Forbid directly switch from the integrated to gpu
Error: switching directly from integrated to Nvidia mode is not supported
Try switching to hybrid mode first!